# Generated by Django 3.2 on 2021-04-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_carrito',
            field=models.CharField(default='8788776', max_length=200),
        ),
    ]
