# Generated by Django 3.2 on 2021-04-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcarts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='no_productos',
            field=models.IntegerField(default=0),
        ),
    ]
