# Generated by Django 3.2 on 2021-04-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ide',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
