# Generated by Django 3.2 on 2021-04-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210415_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ide',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
