# Generated by Django 3.2 on 2021-04-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_ide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(default='Moda,', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(max_length=50),
        ),
    ]
